### ISSUE TITLE
Question about authn_disabled_email

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#12]
Can you explain what `authn_disabled_email` is used for? It's required to be set by config

```yaml
auth:
  authn_disabled_email: foobar@example.com
```

Thx 4 a short note

**Comment by lnobach** [comment]
Some processes (DB storage, ACME provider) need a mandatory e-mail address of the user.
If authn is disabled, this e-mail address is used. Otherwise, it is ignored.
