### ISSUE TITLE
MySQL connection overflow

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#47]
There is a problem with the SQL client lib. The server complains with:
```
dns3l-dns3ld | time="2023-02-20T17:58:40Z" level=info msg="API call for GetCAs" module=service username=anonymous
dns3l-dns3ld | time="2023-02-20T17:58:40Z" level=debug msg="HTTP API call failed with error." error="Error 1040: Too many connections" module=api-v1 path=/api/ca
dns3l-dns3ld | time="2023-02-20T17:58:40Z" level=debug msg="HTTP request failed." message="Error 1040: Too many connections" module=api-v1 path=/api/ca rAddr="172.18.0.7:60896" status=500
```
Is it possible to review and improve daemons connection pooling and handling? Thx.

**Comment by lnobach** [comment]
How many connections are allowed?
A change is difficult, because dns3ld currently handles concurrent calls / jobs by spawning individual DB connections.
We would then need an overlay blocking concurrent DB calls, this will probably slow down response times.
