### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#9]
Dear folks,

thanks a lot for providing your OSS. Enterprises usually requires Auth* and offer AD. Seems [dexidp/dex](https://github.com/dexidp/dex) fits perfectly here.

But our company is not able to model the injected AD group names as described and required by `dns3ld`. A prefix is required and dots (.) are not supported in AD group names.

Is it possible to wash/normalize the `groups[]` entries in ID tokens before doing further authorization? Something like
```
token_group_prefix # default: "", trim
token_group_domain_delim # default: ".", replace with .
```

Otherwise we are not able to use DNS3L with authorization. Without authorization we are not able to offer the service. I also feel the pain of doing this, but inside enterprises you usually not able to control and influence all infrastructure needed like AD in this example.

Thx 4 feedback and consideration.

**Comment by lnobach** [comment]
Yes, this is possible. Planned for the next release.
